version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: fsd1-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: fsd1-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/secureAuthDB
      CLIENT_URL: http://localhost:5173
      JWT_SECRET: ${JWT_SECRET:-change_me_in_dot_env}
      ACCESS_TOKEN_EXPIRES_IN: 15m
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-change_me_too_in_dot_env}
      REFRESH_TOKEN_EXPIRES_IN: 7d
    depends_on:
      - mongo

volumes:
  mongo-data:
